### ISSUE TITLE
add seed to tags

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/script-examples#36]
We should add the seed used when generating a prompt on the tags so we can reproduce the results and add more cool features in the future.

**Comment by l-silvestre** [comment]
also fix in code changing node to register tokens in warp
(fixed on live version on server but official code should also have be fixed)


![Image](https://github.com/FAIR-Protocol/script-examples/assets/43357028/e362df58-3039-4125-aa47-ea70a31c3044)
