### ISSUE TITLE
change uploads to assets on scripts

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/script-examples#64]
We should change the upload of all information to our marketplace as an asset. This way, we can transfer royalties to other persons related to a specific model. This needs changes on scripts, studio and marketplace.

**Comment by l-silvestre** [comment]
Now that models, scrips and promtps are assets, queries need to be updated to properly pick up txs.
Also replace APP-name & App-version to Protocol-name & Protocol-Version
